### ISSUE TITLE
query token_info for snip20/snip721 supposed to be contract_info ?

### ISSUE THREAD

**Issue by agent-mili** [scrtlabs/secret.js#105]
Is this query supposed to query the contract_info instead of token_info:
https://github.com/scrtlabs/secret.js/blob/master/src/extensions/snip721/query.ts#L42-L44
It's just that I cannot find token_info in the specs of snip20/snip721. If so I can do a PR.

**Comment by assafmo** [comment]
> Is this query supposed to query the contract_info instead of token_info?

No, if there's not `token_info` in SNP721, then I vote for removing this function. To query for `contract_info` you can use `secretjs.query.compute.contractInfo()`

**Comment by agent-mili** [comment]
I can create a PR for snp721 extension very soon.
