### ISSUE TITLE
"Cannot set properties of undefined (setting 'tx')" thrown from "broadcastTx" with 1.4.0-alpha.10

### ISSUE THREAD

**Issue by egasimus** [scrtlabs/secret.js#108]
Found with 1.4.0-alpha.4, reproduced with 1.4.0-alpha.10

![Screenshot 2022-09-23 at 0 24 27](https://user-images.githubusercontent.com/1656054/191859256-d7d8e6b1-004a-4f6b-aadc-e17b47f08fc2.jpg)
![signal-2022-09-23-002853_002](https://user-images.githubusercontent.com/1656054/191859317-b95edd5c-6021-49c1-9c05-db6320fd121c.png)
![signal-2022-09-23-003537_002](https://user-images.githubusercontent.com/1656054/191859311-a642bc1a-8ce6-4bab-aff3-871028a182dc.png)

The node returns something with no `txResponse` property so secretjs fails, short-circuiting our subsequent error handling.

**Comment by assafmo** [comment]
Thanks for reporting! I'll take a look

**Comment by assafmo** [comment]
Fixed in `secretjs@1.4.1`

**Comment by assafmo** [comment]
This happens only when the tx broadcast failed, so secret.js will now throw an error
