### ISSUE TITLE
Error broadcasting messages after upgrading to v1.6.9

### ISSUE THREAD

**Issue by SpencerMiller23** [scrtlabs/secret.js#137]
In the lead up to the coming network upgrade, I am trying to upgrade to v1.6.9 which shares the same syntax as v1.7.

However, I am getting this strange error when trying to broadcast any transaction:

`Failed to broadcast transaction ID BF85A9823346E9279E95E2CFAC556A86B203A7140BDB4F1EA5CCA5736DEB55FE: '{"code":3,"message":"must declare at least one event to search","details":[]}'`

Steps to reproduce:
1. Install dependencies: `npm install secretjs@1.6.9`
2. Run the script below: `node ./index.mjs`

Below is a small example that reproduces the issue (Note the file extension is **.mjs**)

`index.mjs`:

```
import { Wallet, SecretNetworkClient, MsgSend, stringToCoins } from 'secretjs'

async function main() {
    try {
        const url = '' // LCD node URL
        const network_id = 'pulsar-2'
    
        const wallet = new Wallet('') // Mnemonic
        const myAddress = wallet.address
    
        const secretClient = new SecretNetworkClient({
            url,
            chainId: network_id,
            wallet: wallet,
            walletAddress: myAddress,
        })

        const msg = new MsgSend({
            from_address: '', // From address
            to_address: '', // To address
            amount: stringToCoins("1uscrt"),
        })
    
        await secretClient.tx.broadcast([msg], {
            gasLimit: 20_000,
            gasPriceInFeeDenom: 0.1,
            feeDenom: 'uscrt',
        })
    } catch (err) {
        console.log(err)
        throw err
    }
}

main()
```

**Comment by assafmo** [comment]
This code works for me with v1.6.9, maybe try switching nodes?

**Comment by SpencerMiller23** [comment]
I was using a link that had a trailing '/' and that was the issue.
