### ISSUE TITLE
transaction failed when write memo on keplr 

### ISSUE THREAD

**Issue by truecode112** [scrtlabs/secret.js#161]
Without memo writing on keplr, broadcast transaction is working well.
But when I input memo on keplr when approving transaction, I am getting this error.
"signature verification failed; please verify account number (22063), sequence (71) and chain-id (pulsar-3): unable to verify single signer signature 3bec5c233a5ff0fc228c04ec33cd1914037f0cf20d72acc02c431c79271f48e21183d7bc093d36840e746bbfe45f3d4415e5b9d960066a4b8ae400d6b3b4f982 for signBytes 7b226163636f756e745f6e756d626572223a223232303633222c22636861696e5f6964223a2270756c7361722d33222c22666565223a7b22616d6f756e74223a5b7b22616d6f756e74223a223330303030222c2264656e6f6d223a227573637274227d5d2c22676173223a22333030303030227d2c226d656d6f223a224d656d6f222c226d736773223a5b7b2274797065223a227761736d2f4d736745786563757465436f6e7472616374222c2276616c7565223a7b22636f6e7472616374223a22736563726574317576303564687074346d33797873656d3375666e74386d64687361356e777761747373726e77222c226d7367223a22354d4f32344965774a495149697249756a58566e3839666830772b584b6e447264424c627a4d4f356e594e45544c556a54444250706458543754354754784654394654507156796541436475686b6b457458684d4b554459434c762f5264704b714c5875436d6f6656757675335667364a456547756c646678353537485a387969417a594a7155654b507a37744f4b6461752b6b7432595732437971594c7379362f53556154425559465a58663458326c2f432f447a56557a507070363369546c597237634858314c624932736175334251554c4f4935504471735633716f7470534a48345a3653487a66324670444549306e653564737561707771455752764b48545947636d732f596d56704364376e764c33466f3575576d476f5a754b766c6c55427372632b69755a697674697a73536a5a7772752b4b42376974412b577956694c457353696f377849536b443678337a726a73703143754957422b446d70506f31415945696d2f4b6c5a6d4b7a32454f2b2b552f6d355247762b5a5965442f426145355261454e6c6466462f744475546c6b2f336f6d4c505264725273564957305a565a3565386537745a6c615963767632386a556470457a584a45386255664b336149494670314749376e52373070524d496143436c576a7766664e573147306771744b2b4357386365654a30733958327371683253686b6c65626f4e4f726532617479222c2273656e646572223a22736563726574313334753433667535667266706c637a637973796d6163396d71326a3268776e366a3335337377222c2273656e745f66756e6473223a5b5d7d7d5d2c2273657175656e6365223a223731227d: unauthorized"

This is my code
const mintMsg = new MsgExecuteContract({
        sender: wallet,
        contract_address: CONTRACT_ADDRESS,
        code_hash: CODE_HASH, // optional but way faster
        msg: {
          mint_nft: {
            owner: wallet,
            public_metadata: publicMetadata,
            private_metadata: privateMetadata,
          },
        },
        sent_funds: [],
      });

      // const sim = await secretClient.tx.simulate([mintMsg]);
      // console.log('sim >>> ', sim);

      let signedTx = await secretClient.tx.signTx([mintMsg], {
        gasLimit: 300_000,
        gasPriceInFeeDenom: 0.1,
        feeDenom: "uscrt",
        memo: "Memo"
      });

      let tx = await secretClient.tx.broadcastSignedTx(signedTx);

***secretClient is the SecretNetworkClient instance.

**Comment by assafmo** [comment]
Thanks for reporting the issue! Fixed in `secretjs@1.12.5`, please try it and let us know if it doesn't work.

**Comment by truecode112** [comment]
Thanks.
It is working well.
