### ISSUE TITLE
package.json incorrect fields? 

### ISSUE THREAD

**Issue by nkrsic** [scrtlabs/secret.js#3]
In package.json, I think the "main" and "types" properties in should be prefixed with `dist/src/` rather than just `dist/`, based on the current Typsecript build behaviour. 

```json
{
  "name": "secretjs",
  "description": "The JavaScript SDK for Secret Network",
  "version": "1.0.2-alpha.2",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
...
```

**Comment by assafmo** [comment]
Hi, you're right, thanks, I'll exclude the test dir from the build. :pray:
