### ISSUE TITLE
tx.authz.MsgRevoke

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/secret.js#76]

**Comment by pyramation** [comment]
https://github.com/osmosis-labs/telescope/blob/379d144ad886e88ee8b752347b680e675e4823eb/packages/osmojs/src/proto/cosmos/authz/v1beta1/tx.amino.ts

looking at the generated code, I see `typeUrl` nested in authz https://github.com/osmosis-labs/telescope/blob/379d144ad886e88ee8b752347b680e675e4823eb/packages/osmojs/src/proto/cosmos/authz/v1beta1/tx.amino.ts#L54

I think this may have been what you were referring to, we'd need a switch statement here for different types.

**Comment by assafmo** [comment]
https://github.com/enigmampc/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/authz/v1beta1/authz.proto#L25

**Comment by assafmo** [comment]
Done & tested
