### ISSUE TITLE
secretjs with local testnet

### ISSUE THREAD

**Issue by stenasd** [scrtlabs/secret.js#77]
gets error "Failed to load resource: the server responded with a status of 426 (Upgrade Required)" and in kepler wallet "Upgrade Required". When testing without kepler with a local wallet i still get 426. Im running latest version of the docker

Crosspost with https://github.com/scrtlabs/SecretJS-Templates/issues/28

**Comment by assafmo** [comment]
Hi, thanks, I'll update https://github.com/scrtlabs/SecretJS-Templates to the new secret.js and hopefully it'll fix it. I'll tag you when I'm done.
