### ISSUE TITLE
Misleading error message on JSON unmarshal error

### ISSUE THREAD

**Issue by egasimus** [scrtlabs/secret.js#79]
![Screenshot from 2022-03-07 13-09-48](https://user-images.githubusercontent.com/1656054/157052300-f8847e80-aed2-4540-839e-00d2a6f33c07.png)

Coulda just went on a wild goose chase upgrading Fadroma to latest secretjs, while the problem was my code 
was passing `memo: []` instead of `memo: ""`. Which as you'll notice has nothing to do with whether I'm using the correct API endpoint, and everything to do with the actual error being swallowed.

**Comment by toml01** [comment]
I was able to reproduce it with the legacy version of secret.js:
```js
client.sendTokens(
    address,
    [{ amount: "100", denom: "uscrt" }],
    [] // memo as an array
  );
```

The [new version of secretjs](https://secretjs.scrt.network/) seems not to have this issue.
We probably should not spend time solving this considering we have a better and more stable version of secretjs.

**Comment by Cashmaney** [comment]
Closing this, then. If anyone encounters such a bug in secretjs 1.x open a new issue with a repro and we'll fix it
